source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!

# 全局设置：所有Pod默认遵循主工程的平台约束
install! 'cocoapods', :deterministic_uuids => false

# 读取主工程的配置（需根据实际项目路径调整）
main_project_path = './XYCgms.xcodeproj'
main_project = Xcodeproj::Project.open(main_project_path)

# 从主工程获取iOS最低部署版本（默认取第一个target的配置）
ios_deployment_target = nil
main_project.targets.each do |target|
  if target.platform_name == :ios
    # 读取主工程target的最低iOS版本
    ios_deployment_target = target.build_configurations.first.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
    break  # 取第一个iOS target的配置
  end
end

# 从主工程获取watchOS最低部署版本（如果有）
watchos_deployment_target = nil
main_project.targets.each do |target|
  if target.platform_name == :watchos
    watchos_deployment_target = target.build_configurations.first.build_settings['WATCHOS_DEPLOYMENT_TARGET']
    break
  end
end

# 确保获取到配置（如果未获取到则使用默认值）
ios_deployment_target ||= '14.0'
watchos_deployment_target ||= '9.0'


$libPath = '../../'

def comPod
  pod 'XYCgms', :path => '../'
  pod 'XYExtension', :path => $libPath + 'XYExtension/'
  pod 'XYUtil', :path => $libPath + 'XYUtil/'
  pod 'XYLog', :path => $libPath + 'XYLog/'
  pod 'XYWorkflow', :path => $libPath + 'XYWorkflow/'
  pod 'XYCoreBluetooth', :path => $libPath + 'XYCoreBluetooth/'
  pod 'XYWatchConnectivity', :path => $libPath + 'XYWatchConnectivity/'
  pod 'XYStorage', :path => $libPath + 'XYStorage/'
  pod 'XYNetwork', :path => $libPath + 'XYNetwork/'
  pod 'MTBleCore', :path => '/Users/huangshanfeng/Desktop/MTBleCore'
  
end

# ====== iOS ====== #
target 'XYCgms' do
  platform :ios, ios_deployment_target
  
  comPod

  target 'XYCgmsTests' do
    inherit! :search_paths
  end

  target 'XYCgmsUITests' do
    inherit! :search_paths
  end
  
end

# ====== watchOS ====== #
target 'XYCgmsWatch Watch App' do
  platform :watchos, watchos_deployment_target
  
  comPod

  target 'XYCgmsWatch Watch AppTests' do
    inherit! :search_paths
  end
  
  target 'XYCgmsWatch Watch AppUITests' do
    inherit! :search_paths
  end
  
end


# 动态同步所有Pod库的配置与主工程一致
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.platform_name == :ios
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = ios_deployment_target
      end
      if target.platform_name == :watchos
        config.build_settings['WATCHOS_DEPLOYMENT_TARGET'] = watchos_deployment_target
      end
      
      # 同步架构配置
      main_archs = main_project.targets.first.build_configurations.first.build_settings['ARCHS']
      if main_archs
        config.build_settings['ARCHS'] = main_archs
      end
    end
  end
end
