use_frameworks!

platform :ios, '10.0'

target 'XYUser_Example' do
  pod 'XYUser', :path => '../'

  target 'XYUser_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
