use_frameworks!

platform :ios, '10.0'

target 'XYApp_Example' do
  pod 'XYApp', :path => '../'

  target 'XYApp_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
