use_frameworks!

platform :ios, '10.0'

target 'XYWatchConnectivity_Example' do
  pod 'XYWatchConnectivity', :path => '../'

  target 'XYWatchConnectivity_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
