use_frameworks!

platform :ios, '10.0'

target 'XYWorkflow_Example' do
  pod 'XYWorkflow', :path => '../'

  target 'XYWorkflow_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
