use_frameworks!

platform :ios, '10.0'

target 'XYCoreBluetooth_Example' do
  pod 'XYCoreBluetooth', :path => '../'

  target 'XYCoreBluetooth_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
